#!/bin/sh

# ------------------------------------------------------------------------------
# Copyright (C) 2013 Schneider-Electric
#
# This file is part of "Mind Compiler" is free software: you can redistribute 
# it and/or modify it under the terms of the GNU Lesser General Public License 
# as published by the Free Software Foundation, either version 3 of the 
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: mind@ow2.org
#
# Authors: Stephane Seyvoz (sseyvoz@assystem.com)
# Contributors: 
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Mind Unit batch script ${project.version}
#
# Required ENV vars:
# ------------------
#   JAVA_HOME - location of a JDK home dir
#
# Optional ENV vars
# -----------------
#   MINDUNIT_HOME - location of mind unit's installed home dir
#   MINDUNIT_OPTS - parameters passed to the Java VM running the mind unit tool
#     e.g. to specify logging levels, use
#       set MINDUNIT_OPTS=-Ddefault.console.level=FINE -Ddefault.file.level=FINER
#   See documentation for more detail on logging system.


# OS specific support.  $var _must_ be set to either true or false.
cygwin=false;
darwin=false;
mingw=false
case "`uname`" in
  CYGWIN*) cygwin=true ;;
  MINGW*) mingw=true;;
  Darwin*) darwin=true 
           if [ -z "$JAVA_VERSION" ] ; then
             JAVA_VERSION="CurrentJDK"
           else
             echo "Using Java version: $JAVA_VERSION"
           fi
           if [ -z "$JAVA_HOME" ] ; then
             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
           fi
           ;;
esac
if [ -z "$JAVA_HOME" ] ; then
  if [ -r /etc/gentoo-release ] ; then
    JAVA_HOME=`java-config --jre-home`
  fi
fi
if [ -z "$MINDUNIT_HOME" ] ; then
  ## resolve links - $0 may be a link to mind unit's home
  PRG="$0"

  # need this for relative symlinks
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
    else
      PRG="`dirname "$PRG"`/$link"
    fi
  done

  saveddir=`pwd`

  MINDUNIT_HOME=`dirname "$PRG"`/..

  # make it fully qualified
  MINDUNIT_HOME=`cd "$MINDUNIT_HOME" && pwd`

  cd "$saveddir"
  # echo Using mindunit at $MINDUNIT_HOME
fi

MINDUNIT_RUNTIME="$MINDUNIT_HOME"/runtime
MINDUNIT_LIB="$MINDUNIT_HOME"/lib
MINDUNIT_EXT="$MINDUNIT_HOME"/ext

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin ; then
  [ -n "$MINDUNIT_HOME" ] &&
    MINDUNIT_HOME=`cygpath --unix "$MINDUNIT_HOME"`
  [ -n "$JAVA_HOME" ] &&
    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
  [ -n "$MINDUNIT_LIB" ] &&
    MINDUNIT_LIB=`cygpath --unix "$MINDUNIT_LIB"`
  [ -n "$MINDUNIT_EXT" ] &&
    MINDUNIT_EXT=`cygpath --unix "$MINDUNIT_EXT"`
  [ -n "$MINDUNIT_RUNTIME" ] &&
    MINDUNIT_RUNTIME=`cygpath --unix "$MINDUNIT_RUNTIME"`
fi

# For Migwn, ensure paths are in UNIX format before anything is touched
if $mingw ; then
  [ -n "$MINDUNIT_HOME" ] &&
    MINDUNIT_HOME="`(cd "$MINDUNIT_HOME"; pwd)`"
  [ -n "$JAVA_HOME" ] &&
    JAVA_HOME="`(cd "$JAVA_HOME"; pwd)`"
  # TODO classpath?
fi


## Launcher class name
LAUNCHER=org.ow2.mind.test.unit.Launcher

## Preparation of the java command to be executed
if [ -z "$JAVACMD" ] ; then
  if [ -n "$JAVA_HOME"  ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
      # IBM's JDK on AIX uses strange locations for the executables
      JAVACMD="$JAVA_HOME/jre/sh/java"
    elif [ -f "$JAVA_HOME"  -a -x "$JAVA_HOME" ] ; then
      # In some cases (such as on TRAVIS CI system) $JAVA_HOME directly point the java executable.
      JAVACMD="$JAVA_HOME"
    else 
      JAVACMD="$JAVA_HOME/bin/java"
    fi
  else
    JAVACMD="`which java`"
  fi
fi

## Print error if the java command is not ready
if [ ! -x "$JAVACMD" ] ; then
  echo "Error: JAVA_HOME is not defined correctly."
  echo "  We cannot execute $JAVACMD"
  exit 1
fi
if [ -z "$JAVA_HOME" ] ; then
  echo "Warning: JAVA_HOME environment variable is not set."
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
  [ -n "$MINDUNIT_HOME" ] &&
    MINDUNIT_HOME=`cygpath --windows "$MINDUNIT_HOME"`
  [ -n "$JAVA_HOME" ] &&
    JAVA_HOME=`cygpath --windows "$JAVA_HOME"`
  [ -n "$HOME" ] &&
    HOME=`cygpath --windows "$HOME"`
  [ -n "$MINDUNIT_LIB" ] &&
    MINDUNIT_LIB=`cygpath --windows "$MINDUNIT_LIB"`
  [ -n "$MINDUNIT_EXT" ] &&
    MINDUNIT_EXT=`cygpath --windows "$MINDUNIT_EXT"`
  [ -n "$MINDUNIT_RUNTIME" ] &&
    MINDUNIT_RUNTIME=`cygpath --windows "$MINDUNIT_RUNTIME"`
fi




for i in "${MINDUNIT_LIB}"/*.jar "${MINDUNIT_EXT}"/*.jar; do
  if [ -z "$MINDUNIT_CLASSPATH" ] ; then
    if $cygwin; then
      lib=`cygpath --windows "${i}"`
      MINDUNIT_CLASSPATH="${lib}"
    else
      MINDUNIT_CLASSPATH="${i}"
    fi
  else
    if $cygwin; then
      lib=`cygpath --windows "${i}"`
      MINDUNIT_CLASSPATH="${MINDUNIT_CLASSPATH};${lib}"
    else
      MINDUNIT_CLASSPATH="${MINDUNIT_CLASSPATH}:${i}"
    fi
  fi
done


##########################################
#echo MINDUNIT_LIB=$MINDUNIT_LIB
#echo MINDUNIT_RUNTIME=$MINDUNIT_RUNTIME
#echo MINDUNIT_CLASSPATH=$MINDUNIT_CLASSPATH
###########################################

exec "$JAVACMD" \
  -classpath "${MINDUNIT_CLASSPATH}" \
  ${MINDUNIT_OPTS} \
  -Dmindunit.launcher.name=mindunit \
  ${LAUNCHER} \
  -src-path="${MINDUNIT_RUNTIME}" \
  "$@"


